-- +goose Up
-- +goose StatementBegin

-- 1. Таблица траекторий с автоматическим ID
CREATE TABLE IF NOT EXISTS trajectories (
                                            trajectory_id bigint GENERATED BY DEFAULT AS IDENTITY,
                                            created_at timestamptz DEFAULT now() NOT NULL,
                                            PRIMARY KEY (trajectory_id)
);

-- 2. Таблица состояний
CREATE TABLE IF NOT EXISTS trajectory_states (
                                                 state_id bigint GENERATED ALWAYS AS IDENTITY,
                                                 trajectory_id bigint NOT NULL,
                                                 position_id bigint NOT NULL, -- Номер шага (1..15)
                                                 state DOUBLE PRECISION[] NOT NULL,
                                                 control DOUBLE PRECISION[] NOT NULL,
                                                 created_at timestamptz DEFAULT now() NOT NULL,
                                                 PRIMARY KEY (state_id),
                                                 FOREIGN KEY (trajectory_id) REFERENCES trajectories(trajectory_id) ON DELETE CASCADE
);

-- ИНДЕКСЫ ДЛЯ СКОРОСТИ:
-- Чтобы быстро находить все состояния конкретной траектории
CREATE INDEX IF NOT EXISTS idx_trajectory_states_trajectory_id ON trajectory_states (trajectory_id);
-- Чтобы Python-скрипт мгновенно находил данные для обучения по шагам (position_id)
CREATE INDEX IF NOT EXISTS idx_trajectory_states_position_id ON trajectory_states (position_id);

-- 3. Таблица результатов (scores)
CREATE TABLE IF NOT EXISTS scores (
                                      score_id bigint GENERATED ALWAYS AS IDENTITY,
                                      trajectory_id bigint NOT NULL UNIQUE,
                                      score DOUBLE PRECISION NOT NULL,
                                      PRIMARY KEY (score_id),
                                      FOREIGN KEY (trajectory_id) REFERENCES trajectories (trajectory_id) ON DELETE CASCADE
);

-- Чтобы ORDER BY score работал быстро при выборке лучших траекторий
CREATE INDEX IF NOT EXISTS idx_scores_score ON scores (score);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS trajectories;
DROP TABLE IF EXISTS trajectory_states;
DROP TABLE IF EXISTS scores;
DROP INDEX IF EXISTS idx_trajectory_states_trajectory_id;
DROP INDEX IF EXISTS idx_trajectory_states_position_id;
DROP INDEX IF EXISTS idx_scores_score;
-- +goose StatementEnd
